language: python
python:
  - 2.6
  - 2.7
  - 3.3
install:
  - pip install -r requirements/pypuppetdb.txt --use-mirrors
  - pip install -r requirements/tests.txt --use-mirrors
script: python setup.py test
notifications:
  email: false
